### ISSUE TITLE
Setup Guidance for the Project

### ISSUE THREAD

**Issue by ayeshaaask** [IlyasKeskinn/e-commerce#1]
Hello [Ilyas Keskin],

I really appreciate your work on this project! I found the source code and demo, and it looks fantastic. However, I noticed that there are no instructions provided for initiating the project. It would be incredibly helpful if you could add setup instructions to assist others in getting started.

Thank you for your great contributions!

Looking forward to your response.

**Comment by ayeshaaask** [comment]
Please take my request in consideration. I'm really looking forward to learn from your project. 🙏🏻

**Comment by IlyasKeskinn** [comment]
Hello,

Thank you for your kind words! I'm glad you found the project and demo to your liking. I noticed that the setup instructions are missing as well, and I will make sure to add them to the README as soon as possible to help others get started easily.

Looking forward to your feedback!

Best regards,
Ilyas Keskin

**Comment by ayeshaaask** [comment]
> Hello,
> 
> Thank you for your kind words! I'm glad you found the project and demo to your liking. I noticed that the setup instructions are missing as well, and I will make sure to add them to the README as soon as possible to help others get started easily.
> 
> Looking forward to your feedback!
> 
> Best regards, Ilyas Keskin

Thank you for your response! I appreciate your willingness to update the README with setup instructions. Since I'm working under a tight deadline, it would be extremely helpful if you could provide the updated instructions as soon as possible. Looking forward to getting started! Thanks again.

**Comment by ayeshaaask** [comment]
Thanks again for your reply! Since I’m on a tight schedule, it would be really helpful if you could update the README with the setup instructions either today or by tomorrow. I truly appreciate your assistance!

________________________________

**Comment by IlyasKeskinn** [comment]
I added the installation steps, you can write if there is an error.

**Comment by ayeshaaask** [comment]
Sure! I'll check it out. I really appreciate your efforts, thanks again!

**Comment by ayeshaaask** [comment]
> I added the installation steps, you can write if there is an error.

I implemented all the installation steps but one issue still persists and that is that when running npm run dev in frontend the frontend, i.e. the homepage is running on port 5173 on browser but nothings working and neither the entire homepage loaded. on the other hand when running npm run start in backend this error is showing up:                                                                                           > backend@1.0.0 start
> npx nodemon index.js

[nodemon] 3.1.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node index.js`
listining on port 3000
(node:18912) [DEP0170] DeprecationWarning: The URL mongodb://skayesha318siddiqa:mymongodb@cluster0-shard-00-02.nxdbz.mongodb.net:27017,cluster0-shard-00-01.nxdbz.mongodb.net:27017,cluster0-shard-00-00.nxdbz.mongodb.net:27017/ecommerceDB?authSource=admin&replicaSet=atlas-edskti-shard-0&retryWrites=true&w=majority&ssl=true is invalid. Future versions of Node.js will throw an error.
(Use `node --trace-deprecation ...` to show where the warning was created)
Succesful connect to mongoDb

but everythings still. i think the frontend is not getting connected with backend neither the server seem to respond. I've been solving this since you provided the installation steps but nothing worked and neither I'm able to understand the main error/reason.

**Comment by ayeshaaask** [comment]
I just posted an error I'm facing please see to it
________________________________

**Comment by ayeshaaask** [comment]
> I added the installation steps, you can write if there is an error.

i implemented all the installation steps, the frontend i.e the homepage as defined in the  file was successfully loaded but when running backend on port 5000, page displaying cannot GET/ error. although i solved it and currently the frontend is running on port 5173 and backend on port 5000(with the message: backend is running). But the core issue is not yet understandable but explained below:
Frontend Not Communicating with Backend and Missing Components on Port 5173

Description: When running the frontend on port 5173, several issues are present:

The frontend is not communicating with the backend.
Only the homepage is visible, and several components are missing or not working:
The slider is not functioning.
Navigation between pages is not working when clicking on links or components.
The navbar is not loaded fully.
The frontend is unable to fetch data from the backend.
Expected Behavior:

The frontend should be able to communicate with the backend, fetching and displaying data properly.
All components should load correctly, including the slider, navbar, and fully functional navigation between pages.

Could you please investigate the connectivity issue between the frontend and backend? We hope this can be resolved as soon as possible to get the application working properly.

Thank you!

**Comment by ayeshaaask** [comment]
> > I added the installation steps, you can write if there is an error.
> 
> i implemented all the installation steps, the frontend i.e the homepage as defined in the file was successfully loaded but when running backend on port 5000, page displaying cannot GET/ error. although i solved it and currently the frontend is running on port 5173 and backend on port 5000(with the message: backend is running). But the core issue is not yet understandable but explained below: Frontend Not Communicating with Backend and Missing Components on Port 5173
> 
> Description: When running the frontend on port 5173, several issues are present:
> 
> The frontend is not communicating with the backend. Only the homepage is visible, and several components are missing or not working: The slider is not functioning. Navigation between pages is not working when clicking on links or components. The navbar is not loaded fully. The frontend is unable to fetch data from the backend. Expected Behavior:
> 
> The frontend should be able to communicate with the backend, fetching and displaying data properly. All components should load correctly, including the slider, navbar, and fully functional navigation between pages.
> 
> Could you please investigate the connectivity issue between the frontend and backend? We hope this can be resolved as soon as possible to get the application working properly.
> 
> Thank you!

Here’s a video showing the issue in action: [Watch the video here](https://www.dropbox.com/scl/fi/y8o4yg54658s01m24hmi5/zephyra.mp4?rlkey=y8wpnjn1mlpa4egq343mji3bp&st=yqmq49ur&dl=0)

**Comment by IlyasKeskinn** [comment]
The "About" section, sliders ,product categories and products in the project are pulled from the database. However, since there is no data in the database at the moment, these sections are not functioning. To resolve this, follow the steps below:

1. User Registration Check:
First, check if the user registration process has been completed. If no user has been created yet, complete the registration process (register).

At this stage, email confirmation is not important, just ensure the registration is successful.
2. Creating an Admin User:
After completing the registration process, log in to your MongoDB panel.

Go to the users collection in your database.
Here, you need to create a user with admin privileges. You can add a new user with the following details:

userName: Ayes Hak
email: yourmail@gmail.com
password: password
userRole: admin
 
This step allows you to define an admin user, giving you access to perform administrative tasks.

3. Restarting the Project:
Once you’ve created the admin user, restart your project.

Then, log in using the admin user credentials you just added to MongoDB.
4. Accessing the Admin Panel:
After logging in, navigate to the following URL in your browser: http://localhost:5173/#/admin.

From the admin panel, you can start adding the necessary content.
5. Adding Data:
In the admin panel, you can manage the following sections and add new data to the database:

Slider Images: Add PNG images for sliders related to product categories.
Top and Sub Categories: You can add and manage product categories.
Products: Add product information and images.
About Section: Add detailed project-related information here.
By following these steps, you will be able to fill in the missing content and manage important data such as sliders, categories, and products through the admin panel.

**Comment by ayeshaaask** [comment]
> The "About" section, sliders ,product categories and products in the project are pulled from the database. However, since there is no data in the database at the moment, these sections are not functioning. To resolve this, follow the steps below:
> 
> 1. User Registration Check:
>    First, check if the user registration process has been completed. If no user has been created yet, complete the registration process (register).
> 
> At this stage, email confirmation is not important, just ensure the registration is successful. 2. Creating an Admin User: After completing the registration process, log in to your MongoDB panel.
> 
> Go to the users collection in your database. Here, you need to create a user with admin privileges. You can add a new user with the following details:
> 
> userName: Ayes Hak email: [yourmail@gmail.com](mailto:yourmail@gmail.com) password: password userRole: admin
> 
> This step allows you to define an admin user, giving you access to perform administrative tasks.
> 
> 3. Restarting the Project:
>    Once you’ve created the admin user, restart your project.
> 
> Then, log in using the admin user credentials you just added to MongoDB. 4. Accessing the Admin Panel: After logging in, navigate to the following URL in your browser: http://localhost:5173/#/admin.
> 
> From the admin panel, you can start adding the necessary content. 5. Adding Data: In the admin panel, you can manage the following sections and add new data to the database:
> 
> Slider Images: Add PNG images for sliders related to product categories. Top and Sub Categories: You can add and manage product categories. Products: Add product information and images. About Section: Add detailed project-related information here. By following these steps, you will be able to fill in the missing content and manage important data such as sliders, categories, and products through the admin panel.

Thank you so much for the detailed instructions! I truly appreciate your guidance and quick response. I’m grateful for your help and support, and I’m excited to move forward with the setup.

Thanks again for your invaluable assistance!

Best regards,
Ayesha Shaikh

**Comment by ayeshaaask** [comment]
> The "About" section, sliders ,product categories and products in the project are pulled from the database. However, since there is no data in the database at the moment, these sections are not functioning. To resolve this, follow the steps below:
> 
> 1. User Registration Check:
>    First, check if the user registration process has been completed. If no user has been created yet, complete the registration process (register).
> 
> At this stage, email confirmation is not important, just ensure the registration is successful. 2. Creating an Admin User: After completing the registration process, log in to your MongoDB panel.
> 
> Go to the users collection in your database. Here, you need to create a user with admin privileges. You can add a new user with the following details:
> 
> userName: Ayes Hak email: [yourmail@gmail.com](mailto:yourmail@gmail.com) password: password userRole: admin
> 
> This step allows you to define an admin user, giving you access to perform administrative tasks.
> 
> 3. Restarting the Project:
>    Once you’ve created the admin user, restart your project.
> 
> Then, log in using the admin user credentials you just added to MongoDB. 4. Accessing the Admin Panel: After logging in, navigate to the following URL in your browser: http://localhost:5173/#/admin.
> 
> From the admin panel, you can start adding the necessary content. 5. Adding Data: In the admin panel, you can manage the following sections and add new data to the database:
> 
> Slider Images: Add PNG images for sliders related to product categories. Top and Sub Categories: You can add and manage product categories. Products: Add product information and images. About Section: Add detailed project-related information here. By following these steps, you will be able to fill in the missing content and manage important data such as sliders, categories, and products through the admin panel.

unable to register 

encountering following errors :

in the backend terminal:
Error: Invalid login: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 41be03b00d2f7-7ea448f93b2sm5327914a12.28 - gsmtp
    at SMTPConnection._formatError (C:\Users\Ayeshashaikh\e-commerce\backend\node_modules\nodemailer\lib\smtp-connection\index.js:798:19)
    at SMTPConnection._actionAUTHComplete (C:\Users\Ayeshashaikh\e-commerce\backend\node_modules\nodemailer\lib\smtp-connection\index.js:1577:34)
    at SMTPConnection.<anonymous> (C:\Users\Ayeshashaikh\e-commerce\backend\node_modules\nodemailer\lib\smtp-connection\index.js:554:26)
    at SMTPConnection._processResponse (C:\Users\Ayeshashaikh\e-commerce\backend\node_modules\nodemailer\lib\smtp-connection\index.js:982:20)
    at SMTPConnection._onData (C:\Users\Ayeshashaikh\e-commerce\backend\node_modules\nodemailer\lib\smtp-connection\index.js:763:14)
    at SMTPConnection._onSocketData (C:\Users\Ayeshashaikh\e-commerce\backend\node_modules\nodemailer\lib\smtp-connection\index.js:195:44)
    at TLSSocket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)     
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'EAUTH',
  response: '535-5.7.8 Username and Password not accepted. For more information, go to\n' +
    '535 5.7.8  https://support.google.com/mail/?p=BadCredentials 41be03b00d2f7-7ea448f93b2sm5327914a12.28 - gsmtp',
  responseCode: 535,
  command: 'AUTH PLAIN'
}
{
  message: 'Invalid login: 535-5.7.8 Username and Password not accepted. For more information, go to\n' +
    '535 5.7.8  https://support.google.com/mail/?p=BadCredentials 41be03b00d2f7-7ea448f93b2sm5327914a12.28 - gsmtp',
  level: 'error',
  timestamp: 'Oct-13-2024 20:53:49'
}


in the console of port 5173(where frontend is running)
[DOM] Found 2 elements with non-unique id #email: (More info: https://goo.gl/9p2vKq) <input class=​" w-100" type=​"text" id=​"email" name=​"email" value>​ <input class=​" w-100" type=​"text" id=​"email" name=​"email" value=​"demo@gmail.com">​Understand this warning
e-commerce/#/login_register:1
 [DOM] Found 2 elements with non-unique id #password: (More info: https://goo.gl/9p2vKq) <input class=​" w-100" type=​"password" id=​"password" name=​"password" value>​ <input class=​" w-100" type=​"password" id=​"password" name=​"password" value=​"122333">​Understand this warning
:5000/auth/register:1 
        
        
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)


on port 5000 console(where backend is running):

Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by ayeshaaask** [comment]
> The "About" section, sliders ,product categories and products in the project are pulled from the database. However, since there is no data in the database at the moment, these sections are not functioning. To resolve this, follow the steps below:
> 
> 1. User Registration Check:
>    First, check if the user registration process has been completed. If no user has been created yet, complete the registration process (register).
> 
> At this stage, email confirmation is not important, just ensure the registration is successful. 2. Creating an Admin User: After completing the registration process, log in to your MongoDB panel.
> 
> Go to the users collection in your database. Here, you need to create a user with admin privileges. You can add a new user with the following details:
> 
> userName: Ayes Hak email: [yourmail@gmail.com](mailto:yourmail@gmail.com) password: password userRole: admin
> 
> This step allows you to define an admin user, giving you access to perform administrative tasks.
> 
> 3. Restarting the Project:
>    Once you’ve created the admin user, restart your project.
> 
> Then, log in using the admin user credentials you just added to MongoDB. 4. Accessing the Admin Panel: After logging in, navigate to the following URL in your browser: http://localhost:5173/#/admin.
> 
> From the admin panel, you can start adding the necessary content. 5. Adding Data: In the admin panel, you can manage the following sections and add new data to the database:
> 
> Slider Images: Add PNG images for sliders related to product categories. Top and Sub Categories: You can add and manage product categories. Products: Add product information and images. About Section: Add detailed project-related information here. By following these steps, you will be able to fill in the missing content and manage important data such as sliders, categories, and products through the admin panel.

as you mentioned that at this stage email confirmation is not important, just ensure the registration is successful. so, the registration is successful! but i have a doubt that Currently, the user is unable to log in because their account isn't confirmed when they click the confirmation link. Can you clarify where the user should be navigated after clicking on the 'confirm account' button? What should the expected flow be after clicking the confirmation link for the user to complete the registration and log in successfully?

looking forward to hearing from you soon!
